# This playbook for apache configuration
<<<<<<< HEAD
# PT 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
# what happen if i cange something

=======
# For test porpose
# Review only
# what happen if i cange something
# GIT FOR FUN
>>>>>>> 425dc40720ee578e18b49dade64a62412bab1e65
---
- name: Install httpd
  hosts: node3
  tasks:
        - name: install httpd
          yum: 
            name: httpd
            state: latest
          
        - name: Start service 
          service: 
            name: httpd
            state: started
            enabled: yes

        - name: allow http to the firewall
          ansible.builtin.lineinfile:
            service: https
            permanent: yes
            state: enabled
           
        - name: Add the line to a file 
          ansible.builtin.lineinfile:
            path: /var/www/html/index.html 
            line: "this is from my playbook"
            create: yes
           
...             
       

