# This playbook for apache configuration
---
- name: Install httpd
  hosts: node3
  tasks:
        - name: install httpd
          yum: 
            name: httpd
            state: latest
          
        - name: Start service 
          service: 
            name: httpd
            state: started
            enabled: yes

        - name: allow http to the firewall
          ansible.builtin.lineinfile:
            service: https
            permanent: yes
            state: enabled
           
        - name: Add the line to a file 
          ansible.builtin.lineinfile:
            path: /var/www/html/index.html 
            line: "this is from my playbook"
            create: yes
           
...             
       

